server:
  port: 10011
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
zuul:
  prefix: /api    #添加路由前缀
  retryable: true
  routes:
    item-service: /item/**
    search-service: /search/**   #搜索服务
    user-service: /user/**   #用户微服务
    auth-service: /auth/**  #授权中心微服务
    cart-service: /cart/**  #购物车服务
    order-service: /order/**  #订单微服务
  ignored-services:
    - upload-service # 忽略upload-service服务
  add-host-header: true  #携带请求本身的head头信息
  sensitive-headers:
hystrix:
  command:
    default:
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            timeoutInMilliseeconds: 5000  #熔断超时时长
ribbon:
  ConnectTimout: 3000 #ribbon链接超时时长
  ReadTimeout: 3000   #ribbon读取超时时长
  MaxAutoRetries: 1  #当前服务重试次数
  MaxAutoRetriesNextServer: 2   #切换服务重试次数
leyou:
  jwt:
    pubKeyPath:  F:/leyouProject/screatKey/rsa/rsa.pub #公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item

