server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://47.110.54.33:3306/leyou?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 10 #10秒不发送就过期
    lease-renewal-interval-in-seconds: 5 #每隔5秒发一次心跳
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印sql日志
