server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 10
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 10 #10秒不发送九过期
    lease-renewal-interval-in-seconds: 5 #每隔5秒发一次心跳

# 静态数据
leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% #登录校验的密钥
    pubKeyPath: F:/leyouProject/screatKey/rsa/rsa.pub #公钥地址
    priKeyPath: F:/leyouProject/screatKey/rsa/rsa.pri #私钥地址
    expire: 30 #过期时间
    cookieName: LY_TOKEN
    cookieMaxAge: 1800  #秒
